name: run backup

on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron: "0 0 * * 0"
  workflow_dispatch:

jobs:
  backup:
    runs-on: ubuntu-latest
    steps:
      - name: download sc-backup
        run: |
          set -e

          PLATFORM=$(python3 -c 'import platform
          def arch() -> str:
              if platform.machine() == "x86_64":
                  return "amd64"
              if "arm" in platform.machine():
                  if "64" in platform.architecture()[0]:
                      return "arm64"
                  else:
                      return "arm"
          def os() -> str:
              return platform.system().lower()
          print(f"{os()}-{arch()}")')

          # Download latest release of sc-backup
          LOCATION=$(curl -s https://api.github.com/repos/mlcdf/sc-backup/releases/latest | grep browser_download_url | grep $PLATFORM | cut -d '"' -f 4)
          echo $LOCATION
          curl -L "${LOCATION}" -o sc-backup

          chmod +x sc-backup

      - name: backup user mlcdf
        run: ./sc-backup --collection mlcdf --pretty

      - name: backup list 'vu au cinéma'
        run: ./sc-backup --list https://www.senscritique.com/liste/Vu_au_cinema/363578 --pretty

      - name: init repo and commit backups
        run: |
          cd output
          git init
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"

          git add .
          git commit -m "Run sc-backup"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.github_token }}
          branch: backup
          force: true
          directory: output
